security:
    encoders:
        Archmage\AdminBundle\Entity\User: sha256

    role_hierarchy:
        ROLE_SUB: ROLE_USER
        ROLE_ADMIN: ROLE_SUB
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: ArchmageAdminBundle:User, property: username }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main
            form_login: 
                always_use_default_target_path: true
                default_target_path: /dashboard
            anonymous: ~
            remember_me:
                key:      "%secret%"
                path:     /
            logout: ~
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }