parameters:
    archmage_admin.user_listener.class: Archmage\AdminBundle\EventListener\UserListener
#    archmage_admin.example.class: Archmage\AdminBundle\Example

services:
    archmage_admin.user_listener:
        class: %archmage_admin.user_listener.class%        
        tags:
            - { name: doctrine.event_listener, event: "prePersist" }
            - { name: doctrine.event_listener, event: "preUpdate" }
        arguments: [@service_container]
